# Generated by Django 3.0.3 on 2020-03-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200306_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_on']},
        ),
    ]
