# Generated by Django 3.0.3 on 2020-06-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_meta_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
